#!/bin/bash
# AUTO-GENERATED by instar PostUpdateMigrator.getMcpHealthAutorefreshHook().
# Auto-recover from an allowlisted MCP that failed to register, by a single
# loop-guarded /sessions/refresh. DARK by default. See the method's doc comment.
set -uo pipefail
INSTAR_DIR="${CLAUDE_PROJECT_DIR:-.}/.instar"
CONFIG="$INSTAR_DIR/config.json"
[ -f "$CONFIG" ] || exit 0

# Enablement: explicit config.mcpAutoRefresh.enabled wins; if UNSET, a DEVELOPMENT
# agent (config.developmentAgent === true — e.g. echo, the dogfooding ground) gets
# it ENABLED, while production agents stay DARK. So "ships dark" means dark on the
# fleet but live on dev agents that prove features first. Explicit false always wins.
ENABLED=$(python3 -c "import json;c=json.load(open('$CONFIG'));e=c.get('mcpAutoRefresh',{}).get('enabled');print(e is True or (e is None and c.get('developmentAgent') is True))" 2>/dev/null || echo False)
[ "$ENABLED" = "True" ] || exit 0

SESSION_ID="${CLAUDE_CODE_SESSION_ID:-}"
[ -n "$SESSION_ID" ] || exit 0
MARKER="$INSTAR_DIR/state/mcp-autorefresh-marker.json"

# Allowlist (default: playwright). Arbitrary failing MCPs must NOT trigger restarts.
ALLOW=$(python3 -c "import json;print(','.join(json.load(open('$CONFIG')).get('mcpAutoRefresh',{}).get('servers',['playwright'])))" 2>/dev/null || echo playwright)
[ -n "$ALLOW" ] || exit 0

# Resolve the claude binary (NOT always on PATH)
CLAUDE_BIN=""
for c in "$(command -v claude 2>/dev/null)" /opt/homebrew/bin/claude "$HOME"/.asdf/installs/nodejs/*/bin/claude; do
  [ -n "$c" ] && [ -x "$c" ] && { CLAUDE_BIN="$c"; break; }
done
[ -n "$CLAUDE_BIN" ] || exit 0

# Bounded 'claude mcp list' — portable timeout LADDER (timeout → gtimeout → perl-alarm),
# mirroring the autonomous stop hook's real-check runner. Bare 'timeout' does not exist
# on coreutils-less macOS (the platform agents actually run on), which previously left
# LIST empty and made this hook SILENTLY INERT in production there. The perl rung maps
# signal-death to 128+signal (GNU-timeout semantics — never $?>>8 alone, whose high
# byte is 0 for a signal-killed child). A bounded runner is REQUIRED: with none present
# we stay dark (exit 0) rather than run the command unbounded.
LIST=""
if command -v timeout >/dev/null 2>&1; then
  LIST=$(timeout 45 "$CLAUDE_BIN" mcp list 2>/dev/null || true)
elif command -v gtimeout >/dev/null 2>&1; then
  LIST=$(gtimeout 45 "$CLAUDE_BIN" mcp list 2>/dev/null || true)
elif command -v perl >/dev/null 2>&1; then
  LIST=$(perl -e 'my($t,@c)=@ARGV; my $p=fork; if($p==0){setpgrp(0,0); exec @c or exit 127} $SIG{ALRM}=sub{kill("-KILL",$p); exit 124}; alarm($t); waitpid($p,0); exit(($?&127) ? 128+($?&127) : ($?>>8))' 45 "$CLAUDE_BIN" mcp list 2>/dev/null || true)
fi
[ -n "$LIST" ] || exit 0

# Allowlisted servers reporting "Failed to connect"
FAILED=""
IFS=',' read -ra ALLOWED <<< "$ALLOW"
for s in "${ALLOWED[@]}"; do
  if echo "$LIST" | grep -iE "^${s}:" | grep -qi "Failed to connect"; then
    FAILED="${FAILED:+$FAILED,}$s"
  fi
done
[ -n "$FAILED" ] || exit 0   # all allowlisted MCPs healthy

# HARD LOOP-GUARD: refresh at most ONCE per (session, failed-set).
if [ -f "$MARKER" ]; then
  PREV=$(python3 -c "import json;d=json.load(open('$MARKER'));print(d.get('sessionId','')+'|'+d.get('failed',''))" 2>/dev/null || echo "")
  if [ "$PREV" = "${SESSION_ID}|${FAILED}" ]; then
    echo "[mcp-autorefresh] $FAILED still failed after one refresh this session — NOT re-refreshing (persistent, not transient)." >&2
    exit 0
  fi
fi

PORT=$(python3 -c "import json;print(json.load(open('$CONFIG')).get('port',4042))" 2>/dev/null || echo 4042)
AUTH="${INSTAR_AUTH_TOKEN:-}"

# Resolve our own tmux session name by matching CLAUDE_CODE_SESSION_ID in /sessions
SNAME=$(curl -s -m 5 -H "Authorization: Bearer $AUTH" "http://localhost:${PORT}/sessions" 2>/dev/null | python3 -c "
import sys,json
sid='$SESSION_ID'
try:
  d=json.load(sys.stdin); arr=d if isinstance(d,list) else d.get('sessions',[])
  for s in arr:
    if sid in (str(s.get('resumeUuid','')), str(s.get('id','')), str(s.get('sessionId',''))):
      print(s.get('tmuxSession') or s.get('name') or ''); break
except Exception:
  pass" 2>/dev/null)
[ -n "$SNAME" ] || { echo "[mcp-autorefresh] could not resolve own session name — skipping refresh." >&2; exit 0; }

# Write the marker BEFORE refreshing so the post-refresh boot sees it and cannot loop
mkdir -p "$INSTAR_DIR/state"
NOW_ISO=$(date -u +%FT%TZ 2>/dev/null || echo "")
python3 -c "import json;json.dump({'sessionId':'$SESSION_ID','failed':'$FAILED','at':'$NOW_ISO'},open('$MARKER','w'))" 2>/dev/null || true

curl -s -m 8 -X POST -H "Authorization: Bearer $AUTH" -H "Content-Type: application/json" \
  "http://localhost:${PORT}/sessions/refresh" \
  -d "{\"sessionName\":\"$SNAME\",\"reason\":\"auto: MCP(s) [$FAILED] failed to connect — refreshing to re-register\"}" >/dev/null 2>&1
echo "[mcp-autorefresh] MCP(s) [$FAILED] failed to connect -> triggered one /sessions/refresh (session $SNAME)." >&2
exit 0
