#!/bin/bash
# Instar boot wrapper — generated by 'instar setup'
# Shadow install is the sole source of truth. No global fallback.
SHADOW="/Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install/node_modules/instar/dist/cli.js"
SHADOW_DIR="/Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install"
CRASH_FILE="/Users/rolandcanyon/.instar/agents/Roland/.instar/state/boot-crashes.txt"

if [ ! -f "$SHADOW" ]; then
  echo "ERROR: Shadow install not found at $SHADOW" >&2
  echo "Run: npm install instar --prefix /Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install" >&2
  exit 1
fi

# Strip extended attributes that may block launchd's restricted sandbox.
# com.apple.quarantine is removable; com.apple.provenance silently fails on macOS 15+.
if command -v xattr >/dev/null 2>&1; then
  xattr -rd com.apple.quarantine "$SHADOW_DIR" 2>/dev/null || true
  xattr -rd com.apple.provenance "$SHADOW_DIR" 2>/dev/null || true
fi

# Crash loop protection: if node fails rapidly, back off before exiting.
# Prevents launchd KeepAlive from spinning at max speed on persistent errors.
mkdir -p "$(dirname "$CRASH_FILE")" 2>/dev/null
node "$SHADOW" "$@"
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "$(date -u +%s)" >> "$CRASH_FILE"
  # Count crashes in the last 120 seconds
  NOW=$(date -u +%s)
  RECENT=$(awk -v now="$NOW" '$1 > now - 120' "$CRASH_FILE" 2>/dev/null | wc -l | tr -d ' ')
  if [ "$RECENT" -ge 3 ]; then
    BACKOFF=$((RECENT * 10))
    [ "$BACKOFF" -gt 120 ] && BACKOFF=120
    echo "[instar-boot] Crash loop detected ($RECENT crashes in 120s). Backing off ${BACKOFF}s..." >&2
    sleep $BACKOFF
  fi
  # Trim crash file to last 20 entries
  tail -20 "$CRASH_FILE" > "$CRASH_FILE.tmp" 2>/dev/null && mv "$CRASH_FILE.tmp" "$CRASH_FILE" 2>/dev/null
  exit $EXIT_CODE
fi

# Clean exit — clear crash history
rm -f "$CRASH_FILE" 2>/dev/null
