#!/usr/bin/env node
/**
 * Instar boot wrapper (Node.js) — generated by 'instar setup'
 *
 * This replaces /bin/bash as the launchd entry point on macOS.
 * On macOS Sequoia+, launchd-spawned /bin/bash lacks Full Disk Access,
 * causing "Operation not permitted" when accessing project files.
 * User-installed node (homebrew, nvm) is not subject to TCC restrictions.
 *
 * Shadow install is the sole source of truth. No global fallback.
 */
const { execFileSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const SHADOW = "/Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install/node_modules/instar/dist/cli.js";
const SHADOW_DIR = "/Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install";
const CRASH_FILE = "/Users/rolandcanyon/.instar/agents/Roland/.instar/state/boot-crashes.txt";
const NODE_SYMLINK = "/Users/rolandcanyon/.instar/agents/Roland/.instar/bin/node";
const NODE_CANDIDATES_FILE = "/Users/rolandcanyon/.instar/agents/Roland/.instar/bin/node-candidates.json";

// ── Self-heal node symlink ──
// Update the stable node symlink to point at the node binary that's
// currently running us. This ensures the NEXT launchd restart will work
// even if node moved (NVM switch, homebrew upgrade) since the last boot.
function selfHealNodeSymlink() {
  try {
    const currentNode = process.execPath;
    const symlinkDir = path.dirname(NODE_SYMLINK);
    fs.mkdirSync(symlinkDir, { recursive: true });

    // Check if symlink already points to current node
    try {
      const target = fs.readlinkSync(NODE_SYMLINK);
      if (target === currentNode) return; // already correct
    } catch { /* broken or missing — will recreate */ }

    // Update symlink
    try { fs.unlinkSync(NODE_SYMLINK); } catch { /* didn't exist */ }
    fs.symlinkSync(currentNode, NODE_SYMLINK);

    // Update candidates file for diagnostics
    const candidates = [currentNode];
    const wellKnown = ['/opt/homebrew/bin/node', '/usr/local/bin/node', '/usr/bin/node'];
    for (const p of wellKnown) {
      if (p !== currentNode && fs.existsSync(p)) candidates.push(p);
    }
    fs.writeFileSync(NODE_CANDIDATES_FILE, JSON.stringify({
      primary: currentNode,
      candidates: candidates,
      updatedAt: new Date().toISOString(),
      updatedBy: 'instar-boot.js',
    }, null, 2));

    process.stderr.write('[instar-boot] Node symlink self-healed: ' + NODE_SYMLINK + ' -> ' + currentNode + '\n');
  } catch (err) {
    // Non-fatal — symlink update is best-effort
    process.stderr.write('[instar-boot] Node symlink self-heal failed (non-critical): ' + err.message + '\n');
  }
}

selfHealNodeSymlink();

// Verify shadow install exists
if (!fs.existsSync(SHADOW)) {
  process.stderr.write('ERROR: Shadow install not found at ' + SHADOW + '\n');
  process.stderr.write('Run: npm install instar --prefix ' + "/Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install" + '\n');
  process.exit(1);
}

// Strip macOS extended attributes that may block launchd's restricted sandbox
if (os.platform() === 'darwin') {
  try {
    execFileSync('xattr', ['-rd', 'com.apple.quarantine', SHADOW_DIR], { stdio: 'ignore' });
  } catch { /* no quarantine to remove — fine */ }
  try {
    execFileSync('xattr', ['-rd', 'com.apple.provenance', SHADOW_DIR], { stdio: 'ignore' });
  } catch { /* provenance is kernel-protected on macOS 15+ — fine */ }
}

// Ensure crash file directory exists
const crashDir = path.dirname(CRASH_FILE);
fs.mkdirSync(crashDir, { recursive: true });

// Spawn the CLI as a child process and wait for exit
const args = process.argv.slice(2);
const child = spawn(process.execPath, [SHADOW, ...args], {
  stdio: 'inherit',
  env: process.env,
});

child.on('exit', (code, signal) => {
  const exitCode = code ?? (signal ? 1 : 0);

  if (exitCode !== 0) {
    // Record crash timestamp
    const now = Math.floor(Date.now() / 1000);
    fs.appendFileSync(CRASH_FILE, now + '\n');

    // Count crashes in the last 120 seconds
    try {
      const lines = fs.readFileSync(CRASH_FILE, 'utf-8').trim().split('\n');
      const cutoff = now - 120;
      const recent = lines.filter(l => parseInt(l, 10) > cutoff).length;

      if (recent >= 3) {
        const backoff = Math.min(recent * 10, 120);
        process.stderr.write('[instar-boot] Crash loop detected (' + recent + ' crashes in 120s). Backing off ' + backoff + 's...\n');
        // Block before exiting so launchd KeepAlive doesn't spin
        execFileSync('sleep', [String(backoff)], { stdio: 'ignore' });
      }

      // Trim crash file to last 20 entries
      if (lines.length > 20) {
        fs.writeFileSync(CRASH_FILE, lines.slice(-20).join('\n') + '\n');
      }
    } catch { /* crash file read failed — not critical */ }

    process.exit(exitCode);
  }

  // Clean exit — clear crash history
  try { fs.unlinkSync(CRASH_FILE); } catch { /* ok */ }
  process.exit(0);
});

child.on('error', (err) => {
  process.stderr.write('[instar-boot] Failed to spawn CLI: ' + err.message + '\n');
  process.exit(1);
});
