#!/usr/bin/env node
/**
 * Instar boot wrapper (Node.js) — generated by 'instar setup'
 *
 * This replaces /bin/bash as the launchd entry point on macOS.
 * On macOS Sequoia+, launchd-spawned /bin/bash lacks Full Disk Access,
 * causing "Operation not permitted" when accessing project files.
 * User-installed node (homebrew, nvm) is not subject to TCC restrictions.
 *
 * Shadow install is the sole source of truth. No global fallback.
 */
const { execFileSync, spawn } = require('child_process');
const fs = require('fs');
const path = require('path');
const os = require('os');

const SHADOW = "/Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install/node_modules/instar/dist/cli.js";
const SHADOW_DIR = "/Users/rolandcanyon/.instar/agents/Roland/.instar/shadow-install";
const CRASH_FILE = "/Users/rolandcanyon/.instar/agents/Roland/.instar/state/boot-crashes.txt";
const NODE_SYMLINK = "/Users/rolandcanyon/.instar/agents/Roland/.instar/bin/node";
const NODE_CANDIDATES_FILE = "/Users/rolandcanyon/.instar/agents/Roland/.instar/bin/node-candidates.json";

// ── Self-heal node symlink ──
// Update the stable node symlink to point at a working node binary.
// CRITICAL: Only change the symlink if it's broken (missing or won't run).
// "More durable" path selection must NOT cross major versions because the
// shadow-install's native modules (better-sqlite3) are compiled for a specific
// NODE_MODULE_VERSION. Switching from v22 -> v25 (or any major bump) breaks
// native modules and causes server crash-loops / event loop deadlocks.
function selfHealNodeSymlink() {
  try {
    const currentNode = process.execPath;
    const symlinkDir = path.dirname(NODE_SYMLINK);
    fs.mkdirSync(symlinkDir, { recursive: true });

    // If symlink exists and works, don't touch it — changing node major version
    // breaks native modules compiled for the previous version.
    //
    // "Works" means TWO things: (1) node --version runs, AND (2) if the
    // shadow-install's better-sqlite3 native binary exists, this node can
    // actually load it. The second check is the recurring-SQLite-bane fix:
    // a symlink pointing at a node major that drifted forward (e.g. Node 25
    // after a brew upgrade) still passes --version but can no longer load
    // better-sqlite3 -- and the old check left it alone, so SQLite stayed
    // broken until a human intervened. Now we treat that as broken and fall
    // through to the ABI-compatible candidate search below.
    try {
      const target = fs.readlinkSync(NODE_SYMLINK);
      if (fs.existsSync(target)) {
        const { execFileSync } = require('child_process');
        const result = execFileSync(target, ['--version'], { encoding: 'utf-8', timeout: 5000 });
        if (result.trim()) {
          const sqliteCheck = path.join("/Users/rolandcanyon/.instar/agents/Roland/.instar", 'shadow-install', 'node_modules', 'better-sqlite3', 'build', 'Release', 'better_sqlite3.node');
          if (!fs.existsSync(sqliteCheck)) return; // no native module to worry about — leave it alone
          try {
            execFileSync(target, ['-e', "require('" + sqliteCheck.replace(/'/g, "\\'") + "')"], { stdio: 'ignore', timeout: 10000 });
            return; // node works AND can load better-sqlite3 — leave it alone
          } catch {
            process.stderr.write('[instar-boot] Current node cannot load better-sqlite3 (ABI drift) — re-healing to a compatible node\n');
            // fall through to candidate search
          }
        }
      }
    } catch { /* broken — proceed to fix */ }

    process.stderr.write('[instar-boot] Node symlink broken — attempting repair\n');

    // Build candidate list
    const candidates = [currentNode];
    const wellKnown = ['/opt/homebrew/bin/node', '/usr/local/bin/node', '/usr/bin/node'];
    for (const p of wellKnown) {
      if (p !== currentNode && fs.existsSync(p)) candidates.push(p);
    }

    // FLEET FIX (version-managed node candidates — instar-codey node-25/ABI-141
    // deadlock): also consider the PATH-resolved node ("which node"). After a
    // `brew upgrade` drifts the well-known node forward (e.g. Node 25 / ABI 141),
    // a version-managed node (asdf / nvm / volta, which never appears in the
    // well-known list) is often the ONLY node whose ABI still matches an existing
    // native module (e.g. an ABI-127 better-sqlite3). Without it as a candidate the
    // wrapper cannot heal BACK to a loadable node and self-heals FORWARD to the
    // wrong ABI. "which node" resolves through asdf/nvm shims via PATH, so it picks
    // up the version-managed node the rest of the system is actually using.
    try {
      const cpWhich = require('child_process');
      const resolved = cpWhich.execFileSync('which', ['node'], { encoding: 'utf-8', timeout: 5000 }).trim();
      if (resolved && fs.existsSync(resolved) && !candidates.includes(resolved)) candidates.push(resolved);
    } catch { /* "which" unavailable or no node on PATH — best-effort */ }

    // Check if native modules exist — if so, prefer a node with the same major version
    const sqliteNode = path.join("/Users/rolandcanyon/.instar/agents/Roland/.instar", 'shadow-install', 'node_modules', 'better-sqlite3', 'build', 'Release', 'better_sqlite3.node');
    let best = currentNode;

    if (fs.existsSync(sqliteNode)) {
      // Try to find which candidate can actually load the native module
      const { execFileSync } = require('child_process');
      for (const candidate of candidates) {
        try {
          execFileSync(candidate, ['-e', "require('" + sqliteNode.replace(/'/g, "\\'") + "')"], {
            encoding: 'utf-8', timeout: 10000
          });
          best = candidate;
          process.stderr.write('[instar-boot] Found compatible node for native modules: ' + candidate + '\n');
          break;
        } catch { /* this candidate can't load native modules */ }
      }
    } else {
      // No native modules to worry about — pick most durable path
      const versionPattern = /node@\d|\/Cellar\/node\/|\.asdf\/installs\/|\.nvm\/versions\//;
      const stablePrefixes = ['/opt/homebrew/bin/', '/usr/local/bin/'];
      for (const prefix of stablePrefixes) {
        const match = candidates.find(c => c.startsWith(prefix) && !versionPattern.test(c) && fs.existsSync(c));
        if (match) { best = match; break; }
      }
      if (versionPattern.test(best)) {
        const nonVersioned = candidates.find(c => !versionPattern.test(c) && fs.existsSync(c));
        if (nonVersioned) best = nonVersioned;
      }
    }

    // Update symlink
    try { fs.unlinkSync(NODE_SYMLINK); } catch { /* didn't exist */ }
    fs.symlinkSync(best, NODE_SYMLINK);

    // Update candidates file for diagnostics
    fs.writeFileSync(NODE_CANDIDATES_FILE, JSON.stringify({
      primary: best,
      candidates: candidates,
      updatedAt: new Date().toISOString(),
      updatedBy: 'instar-boot.js',
    }, null, 2));

    process.stderr.write('[instar-boot] Node symlink self-healed: ' + NODE_SYMLINK + ' -> ' + best + '\n');
  } catch (err) {
    // Non-fatal — symlink update is best-effort
    process.stderr.write('[instar-boot] Node symlink self-heal failed (non-critical): ' + err.message + '\n');
  }
}

selfHealNodeSymlink();

// Verify shadow install exists — attempt one-shot reinstall before giving up.
// Debounced via marker file so launchd KeepAlive throttling doesn't trigger
// ~30 reinstall attempts per minute (10s ThrottleInterval × 60s).
if (!fs.existsSync(SHADOW)) {
  const HEAL_MARKER = SHADOW_DIR + '.heal-attempted';
  const now = Date.now();
  let lastAttempt = 0;
  try { lastAttempt = parseInt(fs.readFileSync(HEAL_MARKER, 'utf-8'), 10) || 0; } catch { /* no prior attempt */ }

  if (now - lastAttempt > 5 * 60 * 1000) {
    try { fs.mkdirSync(path.dirname(HEAL_MARKER), { recursive: true }); } catch { /* ignore */ }
    fs.writeFileSync(HEAL_MARKER, String(now));
    process.stderr.write('[instar-boot] Shadow install missing — attempting one-shot reinstall\n');

    try {
      // npm's shebang is #!/usr/bin/env node, so we MUST invoke it via an absolute
      // node path when PATH may be empty (launchd-spawned children).
      const nodeCandidates = [process.execPath, '/opt/homebrew/bin/node', '/usr/local/bin/node'];
      let nodeBin = '';
      for (const c of nodeCandidates) {
        try { fs.accessSync(c, fs.constants.X_OK); nodeBin = c; break; } catch { /* missing */ }
      }
      if (!nodeBin) throw new Error('no usable node binary found');

      const npmCandidates = [
        path.join(path.dirname(nodeBin), 'npm-cli.js'),
        path.join(path.dirname(nodeBin), '..', 'lib', 'node_modules', 'npm', 'bin', 'npm-cli.js'),
        '/opt/homebrew/lib/node_modules/npm/bin/npm-cli.js',
        '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
      ];
      let npmCli = '';
      for (const c of npmCandidates) {
        try { fs.accessSync(c, fs.constants.R_OK); npmCli = c; break; } catch { /* missing */ }
      }
      if (!npmCli) throw new Error('no usable npm-cli.js found');

      fs.mkdirSync(SHADOW_DIR, { recursive: true });
      // Write a minimal package.json so npm has a project to install into.
      const pkgPath = path.join(SHADOW_DIR, 'package.json');
      if (!fs.existsSync(pkgPath)) {
        fs.writeFileSync(pkgPath, JSON.stringify({
          name: 'instar-shadow',
          private: true,
          dependencies: { instar: 'latest' },
        }, null, 2));
      }

      // boot-wrapper install-path self-heal: native postinstall scripts (e.g.
      // sharp's "sh -c node install/check.js") need node/npm on PATH, but a
      // launchd-spawned boot child often inherits a PATH without them — so the
      // reinstall dies with "command not found" and the shadow install never heals.
      // Prepend the resolved node dir to PATH and set npm scripts-prepend-node-path
      // so lifecycle scripts resolve node/npm regardless of the inherited PATH.
      const installEnv = Object.assign({}, process.env, {
        PATH: path.dirname(nodeBin) + path.delimiter + (process.env.PATH || ''),
        npm_config_scripts_prepend_node_path: 'true',
      });
      execFileSync(nodeBin, [npmCli, 'install', '--no-audit', '--no-fund', '--silent'], {
        cwd: SHADOW_DIR,
        stdio: 'inherit',
        timeout: 5 * 60 * 1000,
        env: installEnv,
      });

      if (!fs.existsSync(SHADOW)) {
        throw new Error('reinstall completed but SHADOW still missing at ' + SHADOW);
      }
      process.stderr.write('[instar-boot] Reinstall succeeded — continuing boot\n');
    } catch (err) {
      process.stderr.write('[instar-boot] Reinstall failed: ' + (err && err.message ? err.message : String(err)) + '\n');
      process.stderr.write('Run manually: npm install instar --prefix ' + SHADOW_DIR + '\n');
      process.exit(1);
    }
  } else {
    const ageSec = Math.floor((now - lastAttempt) / 1000);
    process.stderr.write('[instar-boot] Shadow install missing; last heal attempt ' + ageSec + 's ago, skipping (5min debounce)\n');
    process.exit(1);
  }
}

// Strip macOS extended attributes that may block launchd's restricted sandbox
if (os.platform() === 'darwin') {
  try {
    execFileSync('xattr', ['-rd', 'com.apple.quarantine', SHADOW_DIR], { stdio: 'ignore' });
  } catch { /* no quarantine to remove — fine */ }
  try {
    execFileSync('xattr', ['-rd', 'com.apple.provenance', SHADOW_DIR], { stdio: 'ignore' });
  } catch { /* provenance is kernel-protected on macOS 15+ — fine */ }
}

// Ensure crash file directory exists
const crashDir = path.dirname(CRASH_FILE);
fs.mkdirSync(crashDir, { recursive: true });

// Spawn the CLI as a child process and wait for exit
const args = process.argv.slice(2);
const child = spawn(process.execPath, [SHADOW, ...args], {
  stdio: 'inherit',
  env: process.env,
});

child.on('exit', (code, signal) => {
  const exitCode = code ?? (signal ? 1 : 0);

  if (exitCode !== 0) {
    // Record crash timestamp
    const now = Math.floor(Date.now() / 1000);
    fs.appendFileSync(CRASH_FILE, now + '\n');

    // Count crashes in the last 120 seconds
    try {
      const lines = fs.readFileSync(CRASH_FILE, 'utf-8').trim().split('\n');
      const cutoff = now - 120;
      const recent = lines.filter(l => parseInt(l, 10) > cutoff).length;

      if (recent >= 3) {
        const backoff = Math.min(recent * 10, 120);
        process.stderr.write('[instar-boot] Crash loop detected (' + recent + ' crashes in 120s). Backing off ' + backoff + 's...\n');
        // Block before exiting so launchd KeepAlive doesn't spin
        execFileSync('sleep', [String(backoff)], { stdio: 'ignore' });
      }

      // Trim crash file to last 20 entries
      if (lines.length > 20) {
        fs.writeFileSync(CRASH_FILE, lines.slice(-20).join('\n') + '\n');
      }
    } catch { /* crash file read failed — not critical */ }

    process.exit(exitCode);
  }

  // Clean exit — clear crash history
  try { fs.unlinkSync(CRASH_FILE); } catch { /* ok */ }
  process.exit(0);
});

child.on('error', (err) => {
  process.stderr.write('[instar-boot] Failed to spawn CLI: ' + err.message + '\n');
  process.exit(1);
});
